#!/usr/bin/env ruby
#
# This ruby program prints out the names of all the production machine names
# in the least amount of lines possible.  The output should match the output
# from names-short.rb file.
#
# This is the long version of printing out all the machine names.
#
#---------------------------------------------------------------------------


class MachineNames

  def dump
    puts "c-a-p-1-console.east.sales.com"
    puts "c-a-p-1-console.west.sales.com"
    puts "c-a-p-1.east.sales.com"
    puts "c-a-p-1.west.sales.com"
    puts "c-a-p-2-console.east.sales.com"
    puts "c-a-p-2-console.west.sales.com"
    puts "c-a-p-2.east.sales.com"
    puts "c-a-p-2.west.sales.com"
    puts "c-a-p-3-console.east.sales.com"
    puts "c-a-p-3-console.west.sales.com"
    puts "c-a-p-3.east.sales.com"
    puts "c-a-p-3.west.sales.com"
    puts "g-a-p-1-console.east.sales.com"
    puts "g-a-p-1-console.west.sales.com"
    puts "g-a-p-1.east.sales.com"
    puts "g-a-p-1.west.sales.com"
    puts "g-a-p-2-console.east.sales.com"
    puts "g-a-p-2-console.west.sales.com"
    puts "g-a-p-2.east.sales.com"
    puts "g-a-p-2.west.sales.com"
    puts "g-a-p-3-console.east.sales.com"
    puts "g-a-p-3-console.west.sales.com"
    puts "g-a-p-3.east.sales.com"
    puts "g-a-p-3.west.sales.com"
    puts "g-a-p-4-console.east.sales.com"
    puts "g-a-p-4-console.west.sales.com"
    puts "g-a-p-4.east.sales.com"
    puts "g-a-p-4.west.sales.com"
    puts "g-a-p-5-console.east.sales.com"
    puts "g-a-p-5-console.west.sales.com"
    puts "g-a-p-5.east.sales.com"
    puts "g-a-p-5.west.sales.com"
    puts "g-a-p-6-console.east.sales.com"
    puts "g-a-p-6-console.west.sales.com"
    puts "g-a-p-6.east.sales.com"
    puts "g-a-p-6.west.sales.com"
    puts "g-w-p-1-console.east.sales.com"
    puts "g-w-p-1-console.west.sales.com"
    puts "g-w-p-1.east.sales.com"
    puts "g-w-p-1.west.sales.com"
    puts "g-w-p-2-console.east.sales.com"
    puts "g-w-p-2-console.west.sales.com"
    puts "g-w-p-2.east.sales.com"
    puts "g-w-p-2.west.sales.com"
    puts "g-w-p-3-console.east.sales.com"
    puts "g-w-p-3-console.west.sales.com"
    puts "g-w-p-3.east.sales.com"
    puts "g-w-p-3.west.sales.com"
    puts "g-w-p-4-console.east.sales.com"
    puts "g-w-p-4-console.west.sales.com"
    puts "g-w-p-4.east.sales.com"
    puts "g-w-p-4.west.sales.com"
    puts "s-e-p-1-console.east.sales.com"
    puts "s-e-p-1-console.west.sales.com"
    puts "s-e-p-1.east.sales.com"
    puts "s-e-p-1.west.sales.com"
    puts "s-e-p-2-console.east.sales.com"
    puts "s-e-p-2-console.west.sales.com"
    puts "s-e-p-2.east.sales.com"
    puts "s-e-p-2.west.sales.com"
    puts "s-e-s-1-console.east.sales.com"
    puts "s-e-s-1-console.west.sales.com"
    puts "s-e-s-1.east.sales.com"
    puts "s-e-s-1.west.sales.com"
    puts "s-j-p-1-console.east.sales.com"
    puts "s-j-p-1-console.west.sales.com"
    puts "s-j-p-1.east.sales.com"
    puts "s-j-p-1.west.sales.com"
    puts "s-l-p-1-console.east.sales.com"
    puts "s-l-p-1-console.west.sales.com"
    puts "s-l-p-1.east.sales.com"
    puts "s-l-p-1.west.sales.com"
    puts "s-l-p-2-console.east.sales.com"
    puts "s-l-p-2-console.west.sales.com"
    puts "s-l-p-2.east.sales.com"
    puts "s-l-p-2.west.sales.com"
    puts "s-m-p-1-console.east.sales.com"
    puts "s-m-p-1-console.west.sales.com"
    puts "s-m-p-1.east.sales.com"
    puts "s-m-p-1.west.sales.com"
    puts "s-m-p-2-console.east.sales.com"
    puts "s-m-p-2-console.west.sales.com"
    puts "s-m-p-2.east.sales.com"
    puts "s-m-p-2.west.sales.com"
    puts "s-m-p-3-console.east.sales.com"
    puts "s-m-p-3-console.west.sales.com"
    puts "s-m-p-3.east.sales.com"
    puts "s-m-p-3.west.sales.com"
    puts "s-r-p-1-console.east.sales.com"
    puts "s-r-p-1-console.west.sales.com"
    puts "s-r-p-1.east.sales.com"
    puts "s-r-p-1.west.sales.com"
    puts "s-r-p-2-console.east.sales.com"
    puts "s-r-p-2-console.west.sales.com"
    puts "s-r-p-2.east.sales.com"
    puts "s-r-p-2.west.sales.com"
    puts "umd-a-p-1-console.east.sales.com"
    puts "umd-a-p-1-console.west.sales.com"
    puts "umd-a-p-1.east.sales.com"
    puts "umd-a-p-1.west.sales.com"
    puts "umd-a-p-2-console.east.sales.com"
    puts "umd-a-p-2-console.west.sales.com"
    puts "umd-a-p-2.east.sales.com"
    puts "umd-a-p-2.west.sales.com"
    puts "umd-a-p-3-console.east.sales.com"
    puts "umd-a-p-3-console.west.sales.com"
    puts "umd-a-p-3.east.sales.com"
    puts "umd-a-p-3.west.sales.com"
  end

end

MachineNames.new.dump
